export const blogPosts = [
  {
    title: "Intro",
    slug: "first",
    date: new Date().toString(),
    content:
      "Kære Computer, Velkommen til mit nye nyhedsbrev! Jeg kom engang til at taste forkert med mine pølsefingre i et tweet og skrev nuhedsbrev. Men faktisk tror jeg ikke du skal tage ny delen af dette nyhedsbrev så bogstaveligt. Jeg regner med at jeg her kommer til at grave kaninhuller på rimelig uaktuelle emner. Ingen listicles! Ingen kloge-åge takes på det nyeste nye! Dette er et sted hvor jeg samler mine tanker om de ting der giver mig inspiration til at være teknisk, at programmere, at lære til og fra mig, at bygge ting og at forholde mig kritisk til tekniske økosystemer, værktøjer og paradigmer. Hvert brev er et udpluk af ting jeg finder mening og energi i for tiden, et dybde-dyk ned i områder der altid har fascineret mig, eller udpakning af et emne som trækker i mig. Kære Computer: At skrive kode er på en måde som at føre en slags samtale med min maskine. Computeren har ikke den ringeste snert af humoristisk sans, og er derfor et utrolig hårdt publikum. Det kan være vildt frustrerende at gøre mig forståelig. Så sidder jeg der og gemmer filen med den nyeste rettelse igen-igen mens jeg mumler: Kære Computer, please virk! Eller sværger og kaster hekse-forbandelser. Men computeren er mig kær. Tænk alle de seje ting folk har bygget og alle de sjove ting jeg kan sætte mig for at lære. Nyhedsbrevet er i princippet for alle der er interesserede i teknologi og jeg bestræber mig på at gøre det begyndervenligt for folk der er nye i programmeringens verden.",
  },
  {
    title: "2. blogpost",
    slug: "second",
    date: new Date().toString(),
    content:
      "Kære Computer, Velkommen til mit nye nyhedsbrev! Jeg kom engang til at taste forkert med mine pølsefingre i et tweet og skrev nuhedsbrev. Men faktisk tror jeg ikke du skal tage ny delen af dette nyhedsbrev så bogstaveligt. Jeg regner med at jeg her kommer til at grave kaninhuller på rimelig uaktuelle emner. Ingen listicles! Ingen kloge-åge takes på det nyeste nye! Dette er et sted hvor jeg samler mine tanker om de ting der giver mig inspiration til at være teknisk, at programmere, at lære til og fra mig, at bygge ting og at forholde mig kritisk til tekniske økosystemer, værktøjer og paradigmer. Hvert brev er et udpluk af ting jeg finder mening og energi i for tiden, et dybde-dyk ned i områder der altid har fascineret mig, eller udpakning af et emne som trækker i mig. Kære Computer: At skrive kode er på en måde som at føre en slags samtale med min maskine. Computeren har ikke den ringeste snert af humoristisk sans, og er derfor et utrolig hårdt publikum. Det kan være vildt frustrerende at gøre mig forståelig. Så sidder jeg der og gemmer filen med den nyeste rettelse igen-igen mens jeg mumler: Kære Computer, please virk! Eller sværger og kaster hekse-forbandelser. Men computeren er mig kær. Tænk alle de seje ting folk har bygget og alle de sjove ting jeg kan sætte mig for at lære. Nyhedsbrevet er i princippet for alle der er interesserede i teknologi og jeg bestræber mig på at gøre det begyndervenligt for folk der er nye i programmeringens verden.",
  },
  {
    title: "3. blogpost",
    slug: "third",
    date: new Date().toString(),
    content:
      "Kære Computer, Velkommen til mit nye nyhedsbrev! Jeg kom engang til at taste forkert med mine pølsefingre i et tweet og skrev nuhedsbrev. Men faktisk tror jeg ikke du skal tage ny delen af dette nyhedsbrev så bogstaveligt. Jeg regner med at jeg her kommer til at grave kaninhuller på rimelig uaktuelle emner. Ingen listicles! Ingen kloge-åge takes på det nyeste nye! Dette er et sted hvor jeg samler mine tanker om de ting der giver mig inspiration til at være teknisk, at programmere, at lære til og fra mig, at bygge ting og at forholde mig kritisk til tekniske økosystemer, værktøjer og paradigmer. Hvert brev er et udpluk af ting jeg finder mening og energi i for tiden, et dybde-dyk ned i områder der altid har fascineret mig, eller udpakning af et emne som trækker i mig. Kære Computer: At skrive kode er på en måde som at føre en slags samtale med min maskine. Computeren har ikke den ringeste snert af humoristisk sans, og er derfor et utrolig hårdt publikum. Det kan være vildt frustrerende at gøre mig forståelig. Så sidder jeg der og gemmer filen med den nyeste rettelse igen-igen mens jeg mumler: Kære Computer, please virk! Eller sværger og kaster hekse-forbandelser. Men computeren er mig kær. Tænk alle de seje ting folk har bygget og alle de sjove ting jeg kan sætte mig for at lære. Nyhedsbrevet er i princippet for alle der er interesserede i teknologi og jeg bestræber mig på at gøre det begyndervenligt for folk der er nye i programmeringens verden.",
  },
];
